apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-configmap-reload
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kubernetes-configmap-reload
    spec:
      containers:
      - name: kubernetes-configmap-reload
        image: vijayshegde/spring-petclinic-2.4.5.jar:latest
        ports:
        - containerPort: 8080
          name: http
